# Generated by Django 2.1.7 on 2019-04-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='epass',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
