# Generated by Django 2.1.7 on 2019-04-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdo', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='employee',
            name='eimg',
            field=models.FileField(default=1, upload_to='app/img'),
            preserve_default=False,
        ),
    ]
